FROM python:3.12-slim

# Install psycopg2 dependencies
RUN apt-get update && apt-get install -y \
    libpq-dev \
    gcc \
    && rm -rf /var/lib/apt/lists/*

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

COPY . /app

WORKDIR /app

RUN uv sync --extra cpu

EXPOSE 8080

CMD ["uv", "run", "uvicorn", "persuasio.app:app", "--host", "0.0.0.0", "--port", "8080"]